name: Deploy Django App on Ec2

on:
  push:
    branches: 
      - dev

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - 3.8

    steps:
      - uses: actions/checkout@v2

      - run: virtualenv venv --python=python3
      - run: source venv/bin/activate
      - run: pip install -r requirements.txt

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu/django-blog_app
          remote_host: ec2-13-232-118-94.ap-south-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"